version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm run lint
  tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm test
