version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  default:
    jobs:
      - lint
      - tests
