Description: Capstone stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: prod
      Version: '1.21'
      RoleArn: >-
        arn:aws:iam::012345678910:role/eks-service-role-AWSServiceRoleForAmazonEKS-EXAMPLEBQ4PI
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-852bb683
        SubnetIds:
          - subnet-164b7518
